package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// DARK SCHEME
val DarkBackground = Color(0xFF111318)
val DarkOnBackground = Color(0xFFE2E2E9)
val DarkSurface = Color(0xFF111318)
val DarkOnSurface = Color(0xFFE2E2E9)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC4C6D0)
val DarkSurfaceContainerLowest = Color(0xFF0C0E13)
val DarkSurfaceContainerLow = Color(0xFF191B20)
val DarkSurfaceContainer = Color(0xFF1D2024)
val DarkSurfaceContainerHigh = Color(0xFF282A2F)
val DarkSurfaceContainerHighest = Color(0xFF33353A)
val DarkPrimary = Color(0xFFA8C7FA)
val DarkOnPrimary = Color(0xFF062E6F)
val DarkPrimaryContainer = Color(0xFF0842A0)
val DarkOnPrimaryContainer = Color(0xFFD3E3FD)
val DarkSecondary = Color(0xFFBBC6EA)
val DarkOnSecondary = Color(0xFF253048)
val DarkSecondaryContainer = Color(0xFF3B4866)
val DarkOnSecondaryContainer = Color(0xFFDCE2F9)
val DarkTertiary = Color(0xFF71F7AA)        // online/connected
val DarkOnTertiary = Color(0xFF00381E)
val DarkTertiaryContainer = Color(0xFF00522E)
val DarkOnTertiaryContainer = Color(0xFF8EF7BB)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)

// LIGHT SCHEME
val LightBackground = Color(0xFFFAF9FF)
val LightOnBackground = Color(0xFF1A1B20)
val LightSurface = Color(0xFFFAF9FF)
val LightOnSurface = Color(0xFF1A1B20)
val LightSurfaceVariant = Color(0xFFE0E1E9)
val LightOnSurfaceVariant = Color(0xFF44474F)
val LightSurfaceContainerLowest = Color(0xFFF0F0F7)
val LightSurfaceContainerLow = Color(0xFFF5F4FA)
val LightSurfaceContainer = Color(0xFFFAF9FF)
val LightSurfaceContainerHigh = Color(0xFFECECF2)
val LightSurfaceContainerHighest = Color(0xFFE0E0E7)
val LightPrimary = Color(0xFF1B5ABC)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD5E3FF)
val LightOnPrimaryContainer = Color(0xFF001B3E)
val LightSecondary = Color(0xFF535E78)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDCE2F9)
val LightOnSecondaryContainer = Color(0xFF111B32)
val LightTertiary = Color(0xFF006D41)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF8EF7BB)
val LightOnTertiaryContainer = Color(0xFF002110)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C6CF)
